import type { Metadata } from "next";
import { Geist, Geist_Mono ,Exo} from "next/font/google";
import "./globals.css";
import Navbar from "@/app/_components/Navbar/Navbar";
import Footer from "@/app/_components/Footer/Footer";
import Subnav from "@/app/_components/Subnav/Subnav";
import SubFooter from "@/app/_components/SubFooter/SubFooter";
import { Toaster } from "sonner"
import WrapperForSessionProvider from "./_components/WrapperForSessionProvoder/WrapperForSessionProvider";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import CartContextProvider from '../app/_context/cartContext'
import { getUserCart } from "@/api/services/route.services";
import { CartResponse } from "@/api/types";
import { WishlistProvider } from "../app/_context/wishlistContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const exo = Exo({
  subsets: ['latin'],          
  weight: ['400', '500' ,'600','700'],     
  fallback: ['Arial', 'sans-serif'],
});

export const metadata: Metadata = {
  title: "Freshcart",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const res = await getUserCart();
  (res as CartResponse).products
  return (
    <html
      lang="en"
      className={`${exo.className} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <CartContextProvider res={res}>
           <WishlistProvider>
        <WrapperForSessionProvider>
        <Subnav/>
        <Navbar/>
        {children}
         <Toaster position="top-right"
         toastOptions={{
          classNames:{
            toast:"custom-toast",
          },
         }}
         style={{
          "--normal-text":"#16A34A",
           "--success-text": "#ffb007", 
          "--error-text": "#E7000A",
         }as React.CSSProperties} />
        <SubFooter/>
        <Footer/>
        </WrapperForSessionProvider>
        </WishlistProvider>
        </CartContextProvider>
        </body>
    </html>
  );
}
